org: sergiycheck
app: ws-coin-click
service: ws-coin-click-dynamodb
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Custom Serverless Websockets

  environment:
    USERS_CONNECTIONS_TABLE: ${self:service}-${sls:stage}-users-connections
    USERS_TABLE: ${self:service}-${sls:stage}-users
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_CONNECTIONS_TABLE}"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_TABLE}"

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect

  disconnectionHandler:
    handler: handler.disconnectionHandler
    events:
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default

  increaseCounterHandler:
    handler: handler.increaseCounterHandler
    events:
      - websocket:
          route: increaseCounterHandler

  getUserHandler:
    handler: handler.getUserHandler
    events:
      - websocket:
          route: getUserHandler

  createUserHandler:
    handler: handler.createUserHandler
    events:
      - websocket:
          route: createUserHandler

resources:
  Resources:
    UsersConnectionsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.USERS_CONNECTIONS_TABLE}

    UsersTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

          - AttributeName: connectionId
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: ConnectionIdIdIndex
            KeySchema:
              - AttributeName: connectionId
                KeyType: HASH
            Projection:
              ProjectionType: "KEYS_ONLY"

        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.USERS_TABLE}
